// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPr9n8LmpJ0G-H-wm32_QFJHD8BFhbiDk',
    appId: '1:840320465373:web:caca62730504a6d5621e34',
    messagingSenderId: '840320465373',
    projectId: 'deep-plant-demo',
    authDomain: 'deep-plant-demo.firebaseapp.com',
    storageBucket: 'deep-plant-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe0dxWmbKNRqJgzCUUuaNN6tuwCqxS4Eg',
    appId: '1:840320465373:android:8c09553a2277c6a1621e34',
    messagingSenderId: '840320465373',
    projectId: 'deep-plant-demo',
    storageBucket: 'deep-plant-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXGpK_HKC4hyGLcwHItziGSQeYo-t3Hto',
    appId: '1:840320465373:ios:ab611477af4861b7621e34',
    messagingSenderId: '840320465373',
    projectId: 'deep-plant-demo',
    storageBucket: 'deep-plant-demo.appspot.com',
    iosClientId: '840320465373-te001ptkdjvq2muq5tc3ls5jqhp4jvd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.deepPlant1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXGpK_HKC4hyGLcwHItziGSQeYo-t3Hto',
    appId: '1:840320465373:ios:2046d4436b8e8cd5621e34',
    messagingSenderId: '840320465373',
    projectId: 'deep-plant-demo',
    storageBucket: 'deep-plant-demo.appspot.com',
    iosClientId: '840320465373-ifarn14hr2ejqhn2ine2u8gk5e638507.apps.googleusercontent.com',
    iosBundleId: 'com.example.deepPlant1.RunnerTests',
  );
}
